argo-rollouts:
  dashboard:
    # -- Deploy dashboard server
    enabled: true
    ingress:
      # -- Enable dashboard ingress support
      enabled: true
      # -- Dashboard ingress annotations
      #annotations:
      #  nginx.ingress.kubernetes.io/rewrite-target: /$2
      # -- Dashboard ingress labels
      labels: {}
      # -- Dashboard ingress class name
      ingressClassName: ""

      # -- Dashboard ingress hosts
      ## Argo Rollouts Dashboard Ingress.
      ## Hostnames must be provided if Ingress is enabled.
      ## Secrets must be manually created in the namespace
      hosts: 
        - argo-rollouts.127-0-0-1.nip.io

      # -- Dashboard ingress paths
      # paths:
      #   - /rollouts(/|$)(.*)
      # -- Dashboard ingress path type
      pathType: ImplementationSpecific
